-- AlterTable
ALTER TABLE `Reservation` ADD COLUMN `expiresAt` DATETIME(3) NULL,
    MODIFY `status` ENUM('PENDING', 'CANCELLED', 'COMPLETED') NOT NULL;

-- AlterTable
ALTER TABLE `Seat` MODIFY `status` ENUM('AVAILABLE', 'HELD', 'RESERVED') NOT NULL DEFAULT 'AVAILABLE';
